<?php require './templates/header.phtml' ?>
<?php require './templates/nav.phtml' ?>

<form action="agregarJuego" method="POST">
    <label for="nombre_juego"> Nombre   </label>
    <input type="text" name="nombre_juego">

    <label for="detalle_juego">Detalle</label>
    <input type="text" name="detalle_juego">

    <label for="altura_juego">Altura</label>
    <input type="number" name="altura_juego">
    
    <label for="id_categoria"> Categoria</label>
    <input type="number" name="id_categoria">
        
    <button class="btn btn-success" type="submit"> agregar</button>
</form>
<?php require './templates/footer.phtml' ?>

