<?php require './templates/header.phtml' ?>
<?php require './templates/nav.phtml' ?>

<div>
    <h1>Juegos contenidos en la categoria</h1>

    <ul class="list-group">
        <?php foreach($categoryGames as $cat): ?>
            <li class="list-group-item item-task">
                <div> 
                    <b> <?= $cat->id_juego ?></b> | <?=substr($cat->nombre_juego,0,50)?> 
                </div> 
            </li>
        <?php endforeach ?>
    </ul>

</div>

<?php require './templates/footer.phtml' ?>