
<?php require './templates/header.phtml' ?>

<div>
    <ul class="list-group">
        <?php foreach($games as $game): ?>
            <li class="list-group-item item-task ">
                <div>
                    <b><?= $game->id_juego ?></b> | <?=substr($game->detalle_juego,0,100)?> | <?=substr($game->altura_minima,0,25)?>
                    | <?=substr($game->nombre_categoria,0,50)?>
                </div>
              
            </li>
        <?php endforeach ?>
    </ul>
</div>    

<?php require './templates/footer.phtml' ?>