<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="Styles/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>PARQUE DE DIVERSIONES</title>
</head>
<body>
   
    <header>
        <nav class="navbar">
            <ul>
                <li><a href= "listarCategorias">CATEGORIAS</a></li>
                <li><a href= "listarJuegos">JUEGOS</a></li>
                <li><a class="login-button" href= "login">LOGIN</a></li>
            </ul>
        </nav>
    </header>
    
</body>
</html>