<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="Styles/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>PARQUE DE DIVERSIONES</title>
</head>
<body>
            <?php 
            if (!empty($_SESSION['usuario'])) { ?>
            <a class="btn btn-danger" href="logout">Cerrar sesion</a>
            <?php } else { ?>
                <a class="btn btn-success" href="login">Logearse  </a> 
                <?php } ?>
            </div>

            <a class="btn btn-danger" href="logout">Deslogearse  </a> 
            </div>
        </nav>
    </header>
</body>
</html>
