<?php require './templates/header.phtml' ?>

<div>
    <form action="auth" method="POST">
        <label for="usuario">Usuario</label><input type="text" name="usuario">
        <label for="password">Contraseña</label><input type="password" name="password">

        <?php if (isset($error)) : ?>
            <?= $error ?>
        <?php endif ?>

        <button type="submit">Entrar</button>
    </form>
</div>

