<?php require './templates/header.phtml' ?>

<div class="">
  <form action="auth" method="POST" class="px-4 py-3" >
    <div class="mb-3">
      <label for="usuario" class="form-label">Usuario</label>
      <input type="text" requiere class="form-control" id="usuario" name="usuario" >  
    </div>
    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      <input type="password" requiere class="form-control" id="password" name="password">
    </div>
        <?php if (isset($error)) : ?>
          <?php require './templates/error.phtml' ?>
        <?php endif ?>
        <button type="submit" class="btn btn-primary">Sign in</button>
  </form>
</div> 

<?php require './templates/footer.phtml' ?>

<!-- Comenzamos por lo privado y se nos hizo tarde para hacer el publico.
Nos comprometemos para la ultima entrega realizar todas las consignas y en orden.-->
