<?php require './templates/header.phtml' ?>

<!-- <div>
    <form action="auth" method="POST">
        <label for="usuario">Usuario</label>
        <input type="text" name="usuario">
        <label for="password">Contraseña</label>
        <input type="password" name="password">


        <button type="submit">Entrar</button>
    </form>
</div>
 -->


<div class="dropdown-menu">
  <form class="px-4 py-3" action="auth" method="POST">
    <div class="mb-3">
      <label for="usuario" class="form-label">Usuario</label>
      <input type="text" class="form-control" id="usuario" >  
      <!-- placeholder="email@example.com"> -->
    </div>
    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      <input type="password" class="form-control" id="password" placeholder="Password">
    </div>
    <!-- <div class="mb-3">
      <div class="form-check">
        <input type="checkbox" class="form-check-input" id="dropdownCheck">
        <label class="form-check-label" for="dropdownCheck"> Remember me </label>
      </div>
    </div> -->


    <?php if (isset($error)) : ?>
            <?= $error ?>
        <?php endif ?>
    <button type="submit" class="btn btn-primary">Sign in</button>
  </form>
  <!-- <div class="dropdown-divider"></div> -->
  <!-- <a class="dropdown-item" href="#">New around here? Sign up</a>
  <a class="dropdown-item" href="#">Forgot password?</a> -->
</div>


<?php require './templates/footer.phtml' ?>
