
<!-- 
<form action="modificarJuego" method="POST">
    <label for="nombre"> Nombre </label>
    <input type="text" name="nombre">

    <label for="detalle">Detalle</label>
    <input type="text" name="detalle">

    <label for="altura">Altura</label>
    <input type="number" name="altura">
    
    <label for="id"> Categoria</label>
    <input type="number" name="id">
        
    <button class="btn btn-success" type="submit"> modificar</button>
</form> -->