<header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="listarCategorias">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="listarJuegos">Juegos</a>
                        </li>
                    </ul>
                </div>
                <div>

                    <?php 
                 if (!empty($_SESSION['usuario'])) { ?>
                    <a class="btn btn-danger" href="logout">Cerrar sesion</a>
                    <?php } else { ?>
                        <a class="btn btn-success" href="login">Logearse  </a> 
                        <?php } ?>
                    </div>


                
            </div>
        </nav>
    </header>